name: Build and Deploy Github Pages

env:
    srcDirectory: portfolio
    outputDirectory: portfolio/dist/portfolio

# Only run workflow on pushes to develop or main branches and tags
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: 'cartinx.client/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                    ${{ runner.os }}-node-

            - name: Install Dependencies
              run: |
                cd ${{ env.srcDirectory }}
                npm i

            - name: Build Angular app
              run: |
                cd ${{ env.srcDirectory }}
                npm run build
                
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: githubPage
                path: ${{ env.outputDirectory }}
                if-no-files-found: error
                retention-days: 5
                compression-level: 6

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  merge-multiple: true
            - name: Display structure of downloaded files
              run: ls -R path/to/artifacts
#
#            - name: Fix permissions
#              run: |
#                  chmod -c -R +rX "docs/" | while read line; do
#                    echo "::warning title=Invalid file permissions automatically fixed::$line"
#                  done
#            - name: Upload Pages artifact
#              uses: actions/upload-pages-artifact@v2

